/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.drtech.altbeacon;

import java.util.Collection;
import java.util.HashMap;

import org.altbeacon.beacon.Beacon;
import org.altbeacon.beacon.BeaconConsumer;
import org.altbeacon.beacon.BeaconManager;
import org.altbeacon.beacon.BeaconParser;
import org.altbeacon.beacon.Identifier;
import org.altbeacon.beacon.MonitorNotifier;
import org.altbeacon.beacon.RangeNotifier;
import org.altbeacon.beacon.Region;
import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiConvert;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.ServiceConnection;
import android.os.RemoteException;

/**
 * Events: enteredRegion, exitedRegion, determinedRegionState, beaconProximity
 */
@Kroll.module(name="AltbeaconAndroidModule", id="com.drtech.altbeacon")
public class AndroidAltbeaconModuleModule extends KrollModule implements BeaconConsumer
{
	private static BeaconManager beaconManager;
	private boolean autoRange = true;
	
	// Standard Debugging variables
	private static final String LCAT = "AltbeaconModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public AndroidAltbeaconModuleModule()
	{
		super();
		Log.d(LCAT, "Constructor");
	}
	
	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
		
		beaconManager = BeaconManager.getInstanceForApplication(app);
		
		//Set BeaconLayout for the beacon manager - this must be done before the service is bound
		//See: https://github.com/AltBeacon/android-beacon-library/issues/100
		//addBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24");
		
		beaconManager.setForegroundScanPeriod(1200);
		beaconManager.setForegroundBetweenScanPeriod(2300);
		beaconManager.setBackgroundScanPeriod(10000);
		beaconManager.setBackgroundBetweenScanPeriod(60 * 1000);
		
		//BeaconManager.setDebug(true);
	}
	
	/**
	 * See if Bluetooth 4.0 & LE is available on device
	 *
	 * @return true if iBeacons can be used, false otherwise
	 */
	@Kroll.method
	public boolean checkAvailability() {
		try {
			return beaconManager.checkAvailability();
		} catch (Exception ex) {
			return false;
		}
	}
	
	/**
	 * Binds the activity to the Beacon Service
	 */
	@Kroll.method
	public void bindBeaconService() {
		beaconManager.bind(this);
	}

	/**
	 * Throttles down iBeacon library when app placed in background (but you have to
	 * detect this yourself, this module does not know when apps are put in background).
	 *
	 * @param flag Whether to enable background mode or not.
	 */
	@Kroll.method
	public void setBackgroundMode(boolean flag)
	{
		Log.d(LCAT, "setBackgroundMode: " + flag);

		if (!checkAvailability()) {
			Log.d(LCAT, "Bluetooth LE not available or no permissions on this device");
			return;
		}
		beaconManager.setBackgroundMode(flag);


	}

	/**
	 * Turns on auto ranging. When auto ranging is on, upon entering a region, this
	 * module will automatically begin ranging for beacons within that region, and
	 * stop ranging for beacons when the region is exited. Note ranging requires more
	 * battery power so care should be taken with this setting.
	 */
	@Kroll.method
	public void enableAutoRanging()
	{
		setAutoRange(true);
	}

	/**
	 * Turns off auto ranging. See description of enableAutoRanging for more details.
	 *
	 * @see #enableAutoRanging()
	 */
	@Kroll.method
	public void disableAutoRanging()
	{
		setAutoRange(false);
	}
	
	/**
	 * Turns auto ranging on or off. See description of enableAutoRanging for more details.
	 *
	 * @param autoRange if true, turns on auto ranging. Otherwise, turns it off.
	 *
	 * @see #enableAutoRanging()
	 *
	 */
	@Kroll.method
	public void setAutoRange(boolean autoRange)
	{
		Log.d(LCAT, "setAutoRange: " + autoRange);
		this.autoRange = autoRange;

	}

	/**
	 * Set the scan periods for the bluetooth scanner.
	 *
	 * @param scanPeriods the scan periods.
	 */
	@Kroll.method
	public void setScanPeriods(Object scanPeriods)
	{

		Log.d(LCAT, "setScanPeriods: " + scanPeriods);

		HashMap<String, Object> dict = (HashMap<String, Object>)scanPeriods;

		int foregroundScanPeriod = TiConvert.toInt(dict, "foregroundScanPeriod");
		int foregroundBetweenScanPeriod = TiConvert.toInt(dict, "foregroundBetweenScanPeriod");
		int backgroundScanPeriod = TiConvert.toInt(dict, "backgroundScanPeriod");
		int backgroundBetweenScanPeriod = TiConvert.toInt(dict, "backgroundBetweenScanPeriod");

		beaconManager.setForegroundScanPeriod(foregroundScanPeriod);
		beaconManager.setForegroundBetweenScanPeriod(foregroundBetweenScanPeriod);
		beaconManager.setBackgroundScanPeriod(backgroundScanPeriod);
		beaconManager.setBackgroundBetweenScanPeriod(backgroundBetweenScanPeriod);
	}
	
	/**
	 * Start monitoring a region.
	 * @param region the region to monitor, expected to be a property dictionary from javascript code.
	 */
	@Kroll.method
	public void startMonitoringForRegion(Object region)
	{
		Log.d(LCAT, "startMonitoringForRegion: " + region);

		if (!checkAvailability()) {
			Log.d(LCAT, "Bluetooth LE not available or no permissions on this device");
			return;
		}
		try {
			HashMap<String, Object> dict = (HashMap<String, Object>)region;

			String identifier = TiConvert.toString(dict, "identifier");
			String uuid = TiConvert.toString(dict, "uuid").toLowerCase();
			Integer major = (dict.get("major") != null) ? TiConvert.toInt(dict, "major") : null;
			Integer minor = (dict.get("minor") != null) ? TiConvert.toInt(dict, "minor") : null;

			Identifier id1 = Identifier.parse(uuid);
			Identifier id2 = (major == null) ? null : Identifier.fromInt(major);
			Identifier id3 = (minor == null) ? null : Identifier.fromInt(minor);
			//Region r = new Region(identifier, uuid, major, minor);
			
			Region r = new Region(identifier, id1, id2, id3);

			Log.d(LCAT, "Beginning to monitor region " + r);
			beaconManager.startMonitoringBeaconsInRegion(r);
		} catch (RemoteException ex) {
			Log.e(LCAT, "Cannot start monitoring region " + TiConvert.toString(region, "identifier"), ex);
		}
	}


	/**
	 * Compatibility method for popular iOS FOSS iBeacon library.
	 *
	 * @see #startRangingForRegion(Object)
	 *
	 * @param region the region to range, expected to be a property dictionary from javascript code.
	 */
	@Kroll.method
	public void startRangingForBeacons(Object region) {
		startRangingForRegion(region);
	}
	
	/**
	 * Start ranging a region. You can only range regions into which you have entered.
	 *
	 * @param region the region to range, expected to be a property dictionary from javascript code.
	 */
	@Kroll.method
	public void startRangingForRegion(Object region)
	{
		Log.d(LCAT, "startRangingForRegion: " + region);

		if (!checkAvailability()) {
			Log.d(LCAT, "Bluetooth LE not available or no permissions on this device");
			return;
		}
		try {
			HashMap<String, Object> dict = (HashMap<String, Object>)region;

			String identifier = dict.get("identifier").toString(); //TiConvert.toString(dict, "identifier");
			String uuid = dict.get("uuid").toString(); //TiConvert.toString(dict, "uuid").toLowerCase();
			Integer major = (dict.get("major") != null) ? TiConvert.toInt(dict, "major") : null;
			Integer minor = (dict.get("minor") != null) ? TiConvert.toInt(dict, "minor") : null;

			Identifier id1 = Identifier.parse(uuid);
			Identifier id2 = (major == null) ? null : Identifier.fromInt(major);
			Identifier id3 = (minor == null) ? null : Identifier.fromInt(minor);
			//Region r = new Region(identifier, uuid, major, minor);
			
			Region r = new Region(identifier, id1, id2, id3);
			
			Log.d(LCAT, "Beginning to monitor region " + r);
			beaconManager.startRangingBeaconsInRegion(r);
		} catch (RemoteException ex) {
			Log.e(LCAT, "Cannot start ranging region " + TiConvert.toString(region, "identifier"), ex);
		}
	}
	
	/**
	 * Stop monitoring everything.
	 */
	@Kroll.method
	public void stopMonitoringAllRegions()
	{

		Log.d(LCAT, "stopMonitoringAllRegions");

		for (Region r : beaconManager.getMonitoredRegions()) {
			try {
				beaconManager.stopMonitoringBeaconsInRegion(r);
				Log.d(LCAT, "Stopped monitoring region " + r);
			} catch (RemoteException ex) {
				Log.e(LCAT, "Cannot stop monitoring region " + r.getUniqueId(), ex);
			}
		}

	}

	/**
	 * Stop ranging for everything.
	 */
	@Kroll.method
	public void stopRangingForAllBeacons()
	{

		Log.d(LCAT, "stopRangingForAllBeacons");

		for (Region r : beaconManager.getRangedRegions()) {
			try {
				beaconManager.stopRangingBeaconsInRegion(r);
				Log.d(LCAT, "Stopped ranging region " + r);
			} catch (RemoteException ex) {
				Log.e(LCAT, "Cannot stop ranging region " + r.getUniqueId(), ex);
			}
		}
	}
	
	/**
	 * Add BeaconParser described by layout to the manager
	 */
	@Kroll.method
	public boolean removeBeaconLayout(String layout) {
		Log.d(LCAT, "Removing BeaconLayout: " + layout);
		boolean result = false;
		if (beaconManager.isBound(this)) {
			Log.d(LCAT, "Can't remove from BeaconLayout - service is currently bound");
			return false;
		}
		if (layout != null) {
			result = beaconManager.getBeaconParsers().remove(new BeaconParser().setBeaconLayout(layout));
		}
		return result;
	}
	
	/**
	 * Remove BeaconParser described by layout from the manager
	 */
	@Kroll.method
	public void addBeaconLayout(String layout) {
		Log.d(LCAT, "Adding new BeaconLayout: " + layout);
		if (beaconManager.isBound(this)) {
			Log.d(LCAT, "Can't add a new BeaconLayout - service is currently bound");
			return;
		}
		if (layout != null) {
			beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout(layout));
		}
		
	}
	
	@Override
	public void onStart(Activity activity)
	{
		// This method is called when the module is loaded and the root context is started

		Log.d(LCAT, "[MODULE LIFECYCLE EVENT] start");
		//beaconManager.bind(this);

		super.onStart(activity);
	}

	@Override
	public void onStop(Activity activity)
	{
		// This method is called when the root context is stopped

		Log.d(LCAT, "[MODULE LIFECYCLE EVENT] stop");

		//if (!beaconManager.isBound(this)) {
		//	beaconManager.bind(this);
		//}
		super.onStop(activity);
	}

	@Override
	public void onPause(Activity activity)
	{
		// This method is called when the root context is being suspended

		Log.d(LCAT, "[MODULE LIFECYCLE EVENT] pause");
		//if (!beaconManager.isBound(this)) {
		//	beaconManager.bind(this);
		//}
		
		super.onPause(activity);
	}

	@Override
	public void onResume(Activity activity)
	{
		// This method is called when the root context is being resumed

		Log.d(LCAT, "[MODULE LIFECYCLE EVENT] resume");
		//if (!beaconManager.isBound(this)) {
		//	beaconManager.bind(this);
		//}

		super.onResume(activity);
	}
	
	@Override
	public void onDestroy(Activity activity)
	{
		// This method is called when the root context is being destroyed

		Log.d(LCAT, "[MODULE LIFECYCLE EVENT] destroy");
		//beaconManager.unbind(this);
		if (activity.isFinishing()) {
			Log.d(LCAT, "[MODULE LIFECYCLE EVENT] destroy - isFinishing==true");
			beaconManager.unbind(this);
		}
		super.onDestroy(activity);
	}
	
	public void onBeaconServiceConnect() {

		Log.d(LCAT, "onBeaconServiceConnect");
		beaconManager.setMonitorNotifier(new MonitorNotifier() {

			public void didEnterRegion(Region region) {

				Log.d(LCAT, "Entered region: " + region);

				try {
					if (autoRange) {
						Log.d(LCAT, "Beginning to autoRange region " + region);
						beaconManager.startRangingBeaconsInRegion(region);
					}
					KrollDict e = new KrollDict();
					e.put("identifier", region.getUniqueId());
					fireEvent("enteredRegion", e);
				} catch (RemoteException ex) {
					Log.e(LCAT, "Cannot turn on ranging for region " + region.getUniqueId(), ex);
				}
			}

			public void didExitRegion(Region region) {

				Log.d(LCAT, "Exited region: " + region);

				try {
					beaconManager.stopRangingBeaconsInRegion(region);
					KrollDict e = new KrollDict();
					e.put("identifier", region.getUniqueId());
					fireEvent("exitedRegion", e);
				} catch (RemoteException ex) {
					Log.e(LCAT, "Cannot turn off ranging for region " + region.getUniqueId(), ex);
				}
			}

			public void didDetermineStateForRegion(int state, Region region) {
				if (state == INSIDE) {
					try {
						if (autoRange) {
							Log.d(LCAT, "Beginning to autoRange region " + region);
							beaconManager.startRangingBeaconsInRegion(region);
						}
						KrollDict e = new KrollDict();
						e.put("identifier", region.getUniqueId());
						e.put("regionState", "inside");
						fireEvent("determinedRegionState", e);
					} catch (RemoteException e) {
						Log.e(LCAT, "Cannot turn on ranging for region during didDetermineState" + region);
					}
				} else if (state == OUTSIDE) {
					try {
						beaconManager.stopRangingBeaconsInRegion(region);
						KrollDict e = new KrollDict();
						e.put("identifier", region.getUniqueId());
						e.put("regionState", "outside");
						fireEvent("determinedRegionState", e);
					} catch (RemoteException e) {
						Log.e(LCAT, "Cannot turn off ranging for region during didDetermineState" + region);
					}
				} else {
					Log.d(LCAT, "Unknown region state: " + state + " for region: " + region);
				}

			}
		});

		beaconManager.setRangeNotifier(new RangeNotifier() {
			public void didRangeBeaconsInRegion(Collection<Beacon> iBeacons, Region region) {
				for (Beacon beacon : iBeacons) {
					// identifier, uuid,major,minor,proximity,fromProximity,accuracy,rssi
					KrollDict e = new KrollDict();
					e.put("identifier", region.getUniqueId());
					e.put("uuid", beacon.getId1().toString());
					e.put("major", beacon.getId2().toString());
					e.put("minor", beacon.getId3().toString());
					e.put("proximity", getProximityName((int)beacon.getDistance()));
					e.put("accuracy", beacon.getDistance());
					e.put("rssi", beacon.getRssi());
					e.put("power", beacon.getTxPower());
					fireEvent("beaconProximity", e);
				}
			}

		});

		Log.d(LCAT, "Notifiers set properly - attempting scan");
		HashMap<String, Object> regionData = new HashMap<String, Object>();
		regionData.put("identifer", "TestRegion");
		regionData.put("uuid", "E2C56DB5-DFFB-48D2-B060-D0F5A71096E0");
		//startRangingForRegion(regionData);
	}
	
	//TODO: Fix this
	public static String getProximityName(int p) {
		return "ProximityName";
		/*
		switch (p) {
			case Beacon.PROXIMITY_FAR:
				return "far";
			case Beacon.PROXIMITY_IMMEDIATE:
				return "immediate";
			case Beacon.PROXIMITY_NEAR:
				return "near";
			default:
				return "unknown";
		}
		*/
	}

	// methods to bind and unbind
	public Context getApplicationContext() {
		return super.getActivity().getApplicationContext();
	}

	public void unbindService(ServiceConnection serviceConnection) {
		Log.d(LCAT, "unbindService");
		super.getActivity().unbindService(serviceConnection);
	}

	public boolean bindService(Intent intent, ServiceConnection serviceConnection, int i) {
		Log.d(LCAT, "bindService");
		return super.getActivity().bindService(intent, serviceConnection, i);
	}
}
